Fixes for scripts

diff --git a/home/.config/scripts/pack b/home/.config/scripts/pack
--- a/home/.config/scripts/pack
+++ b/home/.config/scripts/pack
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 
-[ -z "$1" ] && echo "Usage: $0 ARCHIVE_TYPE FILENAME" && return 1
+[ -z "$1" ] && echo "Usage: $0 ARCHIVE_TYPE FILENAME" && exit 1
 
-[ -e "$2" ] || $(echo "Invalid file: '$2'" && return 1)
+[ -e "$2" ] || $(echo "Invalid file: '$2'" && exit 1)
 
 case "$1" in
     tar)
@@ -22,5 +22,5 @@ case "$1" in
     rar)
         rar a "$2.rar" "$2" ;;
     *)
-        echo "Unknown archive type: '$1'" && return 1 ;;
+        echo "Unknown archive type: '$1'" && exit 1 ;;
 esac
